name: learn-github-actions
run-name: ${{ github.actor }} is learning github actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v
  hello-person-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello person action step
        id: hello
        # username/repository_name
        uses: Taiwopeter-babs/learn-github-actions@v0.1
        with:
          who-to-greet: 'Taiwo Babalola'
      # uses the output from the `hello` step
      - name: Get the output time
        run: echo "The time of greeting was ${{ steps.hello.outputs.time }}"